title: Sablière Clark
email: sabliereclark@gmail.com
description: >-
  Sablière Clark est un site d'exploitation et de chargement de sable et de pierre situé au 1483 Chemin Dufresne à Notre-Dame-de-la-Merci.
baseurl: ""
url: "https://sabliereclark.com"

navigation:
  - title: Produits
    url: /produits
  - title: Services
    url: /services
  - title: Entreprise
    url: /compagnie
  - title: Ouverture de compte
    url: /ouverture-compte

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  - produits
  - services

exclude:
  - vendor/
